// Code generated by ent, DO NOT EDIT.

package oauthtoken

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/mwangaben/auth/storage/entstore/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldContainsFold(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldUserID, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldClientID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldName, v))
}

// Scopes applies equality check predicate on the "scopes" field. It's identical to ScopesEQ.
func Scopes(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldScopes, v))
}

// Revoked applies equality check predicate on the "revoked" field. It's identical to RevokedEQ.
func Revoked(v bool) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldRevoked, v))
}

// AccessToken applies equality check predicate on the "access_token" field. It's identical to AccessTokenEQ.
func AccessToken(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldAccessToken, v))
}

// RefreshToken applies equality check predicate on the "refresh_token" field. It's identical to RefreshTokenEQ.
func RefreshToken(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldRefreshToken, v))
}

// AccessExpiresAt applies equality check predicate on the "access_expires_at" field. It's identical to AccessExpiresAtEQ.
func AccessExpiresAt(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldAccessExpiresAt, v))
}

// RefreshExpiresAt applies equality check predicate on the "refresh_expires_at" field. It's identical to RefreshExpiresAtEQ.
func RefreshExpiresAt(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldRefreshExpiresAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldContainsFold(FieldUserID, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDIsNil applies the IsNil predicate on the "client_id" field.
func ClientIDIsNil() predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIsNull(FieldClientID))
}

// ClientIDNotNil applies the NotNil predicate on the "client_id" field.
func ClientIDNotNil() predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotNull(FieldClientID))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldContainsFold(FieldClientID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldContainsFold(FieldName, v))
}

// ScopesEQ applies the EQ predicate on the "scopes" field.
func ScopesEQ(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldScopes, v))
}

// ScopesNEQ applies the NEQ predicate on the "scopes" field.
func ScopesNEQ(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNEQ(FieldScopes, v))
}

// ScopesIn applies the In predicate on the "scopes" field.
func ScopesIn(vs ...string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIn(FieldScopes, vs...))
}

// ScopesNotIn applies the NotIn predicate on the "scopes" field.
func ScopesNotIn(vs ...string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotIn(FieldScopes, vs...))
}

// ScopesGT applies the GT predicate on the "scopes" field.
func ScopesGT(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGT(FieldScopes, v))
}

// ScopesGTE applies the GTE predicate on the "scopes" field.
func ScopesGTE(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGTE(FieldScopes, v))
}

// ScopesLT applies the LT predicate on the "scopes" field.
func ScopesLT(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLT(FieldScopes, v))
}

// ScopesLTE applies the LTE predicate on the "scopes" field.
func ScopesLTE(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLTE(FieldScopes, v))
}

// ScopesContains applies the Contains predicate on the "scopes" field.
func ScopesContains(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldContains(FieldScopes, v))
}

// ScopesHasPrefix applies the HasPrefix predicate on the "scopes" field.
func ScopesHasPrefix(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldHasPrefix(FieldScopes, v))
}

// ScopesHasSuffix applies the HasSuffix predicate on the "scopes" field.
func ScopesHasSuffix(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldHasSuffix(FieldScopes, v))
}

// ScopesIsNil applies the IsNil predicate on the "scopes" field.
func ScopesIsNil() predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIsNull(FieldScopes))
}

// ScopesNotNil applies the NotNil predicate on the "scopes" field.
func ScopesNotNil() predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotNull(FieldScopes))
}

// ScopesEqualFold applies the EqualFold predicate on the "scopes" field.
func ScopesEqualFold(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEqualFold(FieldScopes, v))
}

// ScopesContainsFold applies the ContainsFold predicate on the "scopes" field.
func ScopesContainsFold(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldContainsFold(FieldScopes, v))
}

// RevokedEQ applies the EQ predicate on the "revoked" field.
func RevokedEQ(v bool) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldRevoked, v))
}

// RevokedNEQ applies the NEQ predicate on the "revoked" field.
func RevokedNEQ(v bool) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNEQ(FieldRevoked, v))
}

// AccessTokenEQ applies the EQ predicate on the "access_token" field.
func AccessTokenEQ(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldAccessToken, v))
}

// AccessTokenNEQ applies the NEQ predicate on the "access_token" field.
func AccessTokenNEQ(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNEQ(FieldAccessToken, v))
}

// AccessTokenIn applies the In predicate on the "access_token" field.
func AccessTokenIn(vs ...string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIn(FieldAccessToken, vs...))
}

// AccessTokenNotIn applies the NotIn predicate on the "access_token" field.
func AccessTokenNotIn(vs ...string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotIn(FieldAccessToken, vs...))
}

// AccessTokenGT applies the GT predicate on the "access_token" field.
func AccessTokenGT(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGT(FieldAccessToken, v))
}

// AccessTokenGTE applies the GTE predicate on the "access_token" field.
func AccessTokenGTE(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGTE(FieldAccessToken, v))
}

// AccessTokenLT applies the LT predicate on the "access_token" field.
func AccessTokenLT(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLT(FieldAccessToken, v))
}

// AccessTokenLTE applies the LTE predicate on the "access_token" field.
func AccessTokenLTE(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLTE(FieldAccessToken, v))
}

// AccessTokenContains applies the Contains predicate on the "access_token" field.
func AccessTokenContains(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldContains(FieldAccessToken, v))
}

// AccessTokenHasPrefix applies the HasPrefix predicate on the "access_token" field.
func AccessTokenHasPrefix(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldHasPrefix(FieldAccessToken, v))
}

// AccessTokenHasSuffix applies the HasSuffix predicate on the "access_token" field.
func AccessTokenHasSuffix(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldHasSuffix(FieldAccessToken, v))
}

// AccessTokenEqualFold applies the EqualFold predicate on the "access_token" field.
func AccessTokenEqualFold(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEqualFold(FieldAccessToken, v))
}

// AccessTokenContainsFold applies the ContainsFold predicate on the "access_token" field.
func AccessTokenContainsFold(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldContainsFold(FieldAccessToken, v))
}

// RefreshTokenEQ applies the EQ predicate on the "refresh_token" field.
func RefreshTokenEQ(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldRefreshToken, v))
}

// RefreshTokenNEQ applies the NEQ predicate on the "refresh_token" field.
func RefreshTokenNEQ(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNEQ(FieldRefreshToken, v))
}

// RefreshTokenIn applies the In predicate on the "refresh_token" field.
func RefreshTokenIn(vs ...string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIn(FieldRefreshToken, vs...))
}

// RefreshTokenNotIn applies the NotIn predicate on the "refresh_token" field.
func RefreshTokenNotIn(vs ...string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotIn(FieldRefreshToken, vs...))
}

// RefreshTokenGT applies the GT predicate on the "refresh_token" field.
func RefreshTokenGT(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGT(FieldRefreshToken, v))
}

// RefreshTokenGTE applies the GTE predicate on the "refresh_token" field.
func RefreshTokenGTE(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGTE(FieldRefreshToken, v))
}

// RefreshTokenLT applies the LT predicate on the "refresh_token" field.
func RefreshTokenLT(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLT(FieldRefreshToken, v))
}

// RefreshTokenLTE applies the LTE predicate on the "refresh_token" field.
func RefreshTokenLTE(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLTE(FieldRefreshToken, v))
}

// RefreshTokenContains applies the Contains predicate on the "refresh_token" field.
func RefreshTokenContains(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldContains(FieldRefreshToken, v))
}

// RefreshTokenHasPrefix applies the HasPrefix predicate on the "refresh_token" field.
func RefreshTokenHasPrefix(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldHasPrefix(FieldRefreshToken, v))
}

// RefreshTokenHasSuffix applies the HasSuffix predicate on the "refresh_token" field.
func RefreshTokenHasSuffix(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldHasSuffix(FieldRefreshToken, v))
}

// RefreshTokenIsNil applies the IsNil predicate on the "refresh_token" field.
func RefreshTokenIsNil() predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIsNull(FieldRefreshToken))
}

// RefreshTokenNotNil applies the NotNil predicate on the "refresh_token" field.
func RefreshTokenNotNil() predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotNull(FieldRefreshToken))
}

// RefreshTokenEqualFold applies the EqualFold predicate on the "refresh_token" field.
func RefreshTokenEqualFold(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEqualFold(FieldRefreshToken, v))
}

// RefreshTokenContainsFold applies the ContainsFold predicate on the "refresh_token" field.
func RefreshTokenContainsFold(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldContainsFold(FieldRefreshToken, v))
}

// AccessExpiresAtEQ applies the EQ predicate on the "access_expires_at" field.
func AccessExpiresAtEQ(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldAccessExpiresAt, v))
}

// AccessExpiresAtNEQ applies the NEQ predicate on the "access_expires_at" field.
func AccessExpiresAtNEQ(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNEQ(FieldAccessExpiresAt, v))
}

// AccessExpiresAtIn applies the In predicate on the "access_expires_at" field.
func AccessExpiresAtIn(vs ...time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIn(FieldAccessExpiresAt, vs...))
}

// AccessExpiresAtNotIn applies the NotIn predicate on the "access_expires_at" field.
func AccessExpiresAtNotIn(vs ...time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotIn(FieldAccessExpiresAt, vs...))
}

// AccessExpiresAtGT applies the GT predicate on the "access_expires_at" field.
func AccessExpiresAtGT(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGT(FieldAccessExpiresAt, v))
}

// AccessExpiresAtGTE applies the GTE predicate on the "access_expires_at" field.
func AccessExpiresAtGTE(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGTE(FieldAccessExpiresAt, v))
}

// AccessExpiresAtLT applies the LT predicate on the "access_expires_at" field.
func AccessExpiresAtLT(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLT(FieldAccessExpiresAt, v))
}

// AccessExpiresAtLTE applies the LTE predicate on the "access_expires_at" field.
func AccessExpiresAtLTE(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLTE(FieldAccessExpiresAt, v))
}

// RefreshExpiresAtEQ applies the EQ predicate on the "refresh_expires_at" field.
func RefreshExpiresAtEQ(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldRefreshExpiresAt, v))
}

// RefreshExpiresAtNEQ applies the NEQ predicate on the "refresh_expires_at" field.
func RefreshExpiresAtNEQ(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNEQ(FieldRefreshExpiresAt, v))
}

// RefreshExpiresAtIn applies the In predicate on the "refresh_expires_at" field.
func RefreshExpiresAtIn(vs ...time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIn(FieldRefreshExpiresAt, vs...))
}

// RefreshExpiresAtNotIn applies the NotIn predicate on the "refresh_expires_at" field.
func RefreshExpiresAtNotIn(vs ...time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotIn(FieldRefreshExpiresAt, vs...))
}

// RefreshExpiresAtGT applies the GT predicate on the "refresh_expires_at" field.
func RefreshExpiresAtGT(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGT(FieldRefreshExpiresAt, v))
}

// RefreshExpiresAtGTE applies the GTE predicate on the "refresh_expires_at" field.
func RefreshExpiresAtGTE(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGTE(FieldRefreshExpiresAt, v))
}

// RefreshExpiresAtLT applies the LT predicate on the "refresh_expires_at" field.
func RefreshExpiresAtLT(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLT(FieldRefreshExpiresAt, v))
}

// RefreshExpiresAtLTE applies the LTE predicate on the "refresh_expires_at" field.
func RefreshExpiresAtLTE(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLTE(FieldRefreshExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OAuthToken) predicate.OAuthToken {
	return predicate.OAuthToken(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OAuthToken) predicate.OAuthToken {
	return predicate.OAuthToken(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OAuthToken) predicate.OAuthToken {
	return predicate.OAuthToken(sql.NotPredicates(p))
}
