// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// OAuthClient is the predicate function for oauthclient builders.
type OAuthClient func(*sql.Selector)

// OAuthPersonalAccessToken is the predicate function for oauthpersonalaccesstoken builders.
type OAuthPersonalAccessToken func(*sql.Selector)

// OAuthToken is the predicate function for oauthtoken builders.
type OAuthToken func(*sql.Selector)
