// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// OauthClientsColumns holds the columns for the "oauth_clients" table.
	OauthClientsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "secret", Type: field.TypeString},
		{Name: "redirect_uri", Type: field.TypeString, Nullable: true},
		{Name: "personal_access_client", Type: field.TypeBool, Default: false},
		{Name: "password_client", Type: field.TypeBool, Default: false},
		{Name: "revoked", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// OauthClientsTable holds the schema information for the "oauth_clients" table.
	OauthClientsTable = &schema.Table{
		Name:       "oauth_clients",
		Columns:    OauthClientsColumns,
		PrimaryKey: []*schema.Column{OauthClientsColumns[0]},
	}
	// OauthPersonalAccessTokensColumns holds the columns for the "oauth_personal_access_tokens" table.
	OauthPersonalAccessTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "token_id", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "revoked", Type: field.TypeBool, Default: false},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// OauthPersonalAccessTokensTable holds the schema information for the "oauth_personal_access_tokens" table.
	OauthPersonalAccessTokensTable = &schema.Table{
		Name:       "oauth_personal_access_tokens",
		Columns:    OauthPersonalAccessTokensColumns,
		PrimaryKey: []*schema.Column{OauthPersonalAccessTokensColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "oauthpersonalaccesstoken_token_id",
				Unique:  false,
				Columns: []*schema.Column{OauthPersonalAccessTokensColumns[1]},
			},
			{
				Name:    "oauthpersonalaccesstoken_user_id",
				Unique:  false,
				Columns: []*schema.Column{OauthPersonalAccessTokensColumns[2]},
			},
		},
	}
	// OauthTokensColumns holds the columns for the "oauth_tokens" table.
	OauthTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "user_id", Type: field.TypeString},
		{Name: "client_id", Type: field.TypeString, Nullable: true},
		{Name: "name", Type: field.TypeString, Nullable: true},
		{Name: "scopes", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "revoked", Type: field.TypeBool, Default: false},
		{Name: "access_token", Type: field.TypeString, Size: 2147483647},
		{Name: "refresh_token", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// OauthTokensTable holds the schema information for the "oauth_tokens" table.
	OauthTokensTable = &schema.Table{
		Name:       "oauth_tokens",
		Columns:    OauthTokensColumns,
		PrimaryKey: []*schema.Column{OauthTokensColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "oauthtoken_user_id",
				Unique:  false,
				Columns: []*schema.Column{OauthTokensColumns[1]},
			},
			{
				Name:    "oauthtoken_client_id",
				Unique:  false,
				Columns: []*schema.Column{OauthTokensColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		OauthClientsTable,
		OauthPersonalAccessTokensTable,
		OauthTokensTable,
	}
)

func init() {
}
