// Code generated by ent, DO NOT EDIT.

package oauthpersonalaccesstoken

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/mwangaben/auth/storage/entstore/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldContainsFold(FieldID, id))
}

// TokenID applies equality check predicate on the "token_id" field. It's identical to TokenIDEQ.
func TokenID(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldEQ(FieldTokenID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldEQ(FieldUserID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldEQ(FieldName, v))
}

// Revoked applies equality check predicate on the "revoked" field. It's identical to RevokedEQ.
func Revoked(v bool) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldEQ(FieldRevoked, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldEQ(FieldUpdatedAt, v))
}

// TokenIDEQ applies the EQ predicate on the "token_id" field.
func TokenIDEQ(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldEQ(FieldTokenID, v))
}

// TokenIDNEQ applies the NEQ predicate on the "token_id" field.
func TokenIDNEQ(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldNEQ(FieldTokenID, v))
}

// TokenIDIn applies the In predicate on the "token_id" field.
func TokenIDIn(vs ...string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldIn(FieldTokenID, vs...))
}

// TokenIDNotIn applies the NotIn predicate on the "token_id" field.
func TokenIDNotIn(vs ...string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldNotIn(FieldTokenID, vs...))
}

// TokenIDGT applies the GT predicate on the "token_id" field.
func TokenIDGT(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldGT(FieldTokenID, v))
}

// TokenIDGTE applies the GTE predicate on the "token_id" field.
func TokenIDGTE(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldGTE(FieldTokenID, v))
}

// TokenIDLT applies the LT predicate on the "token_id" field.
func TokenIDLT(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldLT(FieldTokenID, v))
}

// TokenIDLTE applies the LTE predicate on the "token_id" field.
func TokenIDLTE(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldLTE(FieldTokenID, v))
}

// TokenIDContains applies the Contains predicate on the "token_id" field.
func TokenIDContains(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldContains(FieldTokenID, v))
}

// TokenIDHasPrefix applies the HasPrefix predicate on the "token_id" field.
func TokenIDHasPrefix(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldHasPrefix(FieldTokenID, v))
}

// TokenIDHasSuffix applies the HasSuffix predicate on the "token_id" field.
func TokenIDHasSuffix(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldHasSuffix(FieldTokenID, v))
}

// TokenIDEqualFold applies the EqualFold predicate on the "token_id" field.
func TokenIDEqualFold(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldEqualFold(FieldTokenID, v))
}

// TokenIDContainsFold applies the ContainsFold predicate on the "token_id" field.
func TokenIDContainsFold(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldContainsFold(FieldTokenID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldContainsFold(FieldUserID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldContainsFold(FieldName, v))
}

// RevokedEQ applies the EQ predicate on the "revoked" field.
func RevokedEQ(v bool) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldEQ(FieldRevoked, v))
}

// RevokedNEQ applies the NEQ predicate on the "revoked" field.
func RevokedNEQ(v bool) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldNEQ(FieldRevoked, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldLTE(FieldExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OAuthPersonalAccessToken) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OAuthPersonalAccessToken) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OAuthPersonalAccessToken) predicate.OAuthPersonalAccessToken {
	return predicate.OAuthPersonalAccessToken(sql.NotPredicates(p))
}
