// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mwangaben/auth/storage/entstore/ent/oauthpersonalaccesstoken"
)

// OAuthPersonalAccessTokenCreate is the builder for creating a OAuthPersonalAccessToken entity.
type OAuthPersonalAccessTokenCreate struct {
	config
	mutation *OAuthPersonalAccessTokenMutation
	hooks    []Hook
}

// SetTokenID sets the "token_id" field.
func (_c *OAuthPersonalAccessTokenCreate) SetTokenID(v string) *OAuthPersonalAccessTokenCreate {
	_c.mutation.SetTokenID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *OAuthPersonalAccessTokenCreate) SetUserID(v string) *OAuthPersonalAccessTokenCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *OAuthPersonalAccessTokenCreate) SetName(v string) *OAuthPersonalAccessTokenCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetRevoked sets the "revoked" field.
func (_c *OAuthPersonalAccessTokenCreate) SetRevoked(v bool) *OAuthPersonalAccessTokenCreate {
	_c.mutation.SetRevoked(v)
	return _c
}

// SetNillableRevoked sets the "revoked" field if the given value is not nil.
func (_c *OAuthPersonalAccessTokenCreate) SetNillableRevoked(v *bool) *OAuthPersonalAccessTokenCreate {
	if v != nil {
		_c.SetRevoked(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *OAuthPersonalAccessTokenCreate) SetExpiresAt(v time.Time) *OAuthPersonalAccessTokenCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OAuthPersonalAccessTokenCreate) SetCreatedAt(v time.Time) *OAuthPersonalAccessTokenCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OAuthPersonalAccessTokenCreate) SetNillableCreatedAt(v *time.Time) *OAuthPersonalAccessTokenCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OAuthPersonalAccessTokenCreate) SetUpdatedAt(v time.Time) *OAuthPersonalAccessTokenCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OAuthPersonalAccessTokenCreate) SetNillableUpdatedAt(v *time.Time) *OAuthPersonalAccessTokenCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OAuthPersonalAccessTokenCreate) SetID(v string) *OAuthPersonalAccessTokenCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the OAuthPersonalAccessTokenMutation object of the builder.
func (_c *OAuthPersonalAccessTokenCreate) Mutation() *OAuthPersonalAccessTokenMutation {
	return _c.mutation
}

// Save creates the OAuthPersonalAccessToken in the database.
func (_c *OAuthPersonalAccessTokenCreate) Save(ctx context.Context) (*OAuthPersonalAccessToken, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuthPersonalAccessTokenCreate) SaveX(ctx context.Context) *OAuthPersonalAccessToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthPersonalAccessTokenCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthPersonalAccessTokenCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuthPersonalAccessTokenCreate) defaults() {
	if _, ok := _c.mutation.Revoked(); !ok {
		v := oauthpersonalaccesstoken.DefaultRevoked
		_c.mutation.SetRevoked(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oauthpersonalaccesstoken.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := oauthpersonalaccesstoken.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuthPersonalAccessTokenCreate) check() error {
	if _, ok := _c.mutation.TokenID(); !ok {
		return &ValidationError{Name: "token_id", err: errors.New(`ent: missing required field "OAuthPersonalAccessToken.token_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "OAuthPersonalAccessToken.user_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "OAuthPersonalAccessToken.name"`)}
	}
	if _, ok := _c.mutation.Revoked(); !ok {
		return &ValidationError{Name: "revoked", err: errors.New(`ent: missing required field "OAuthPersonalAccessToken.revoked"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "OAuthPersonalAccessToken.expires_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OAuthPersonalAccessToken.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OAuthPersonalAccessToken.updated_at"`)}
	}
	return nil
}

func (_c *OAuthPersonalAccessTokenCreate) sqlSave(ctx context.Context) (*OAuthPersonalAccessToken, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected OAuthPersonalAccessToken.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuthPersonalAccessTokenCreate) createSpec() (*OAuthPersonalAccessToken, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthPersonalAccessToken{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthpersonalaccesstoken.Table, sqlgraph.NewFieldSpec(oauthpersonalaccesstoken.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TokenID(); ok {
		_spec.SetField(oauthpersonalaccesstoken.FieldTokenID, field.TypeString, value)
		_node.TokenID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(oauthpersonalaccesstoken.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(oauthpersonalaccesstoken.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Revoked(); ok {
		_spec.SetField(oauthpersonalaccesstoken.FieldRevoked, field.TypeBool, value)
		_node.Revoked = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthpersonalaccesstoken.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oauthpersonalaccesstoken.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthpersonalaccesstoken.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OAuthPersonalAccessTokenCreateBulk is the builder for creating many OAuthPersonalAccessToken entities in bulk.
type OAuthPersonalAccessTokenCreateBulk struct {
	config
	err      error
	builders []*OAuthPersonalAccessTokenCreate
}

// Save creates the OAuthPersonalAccessToken entities in the database.
func (_c *OAuthPersonalAccessTokenCreateBulk) Save(ctx context.Context) ([]*OAuthPersonalAccessToken, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuthPersonalAccessToken, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthPersonalAccessTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuthPersonalAccessTokenCreateBulk) SaveX(ctx context.Context) []*OAuthPersonalAccessToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthPersonalAccessTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthPersonalAccessTokenCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
