// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mwangaben/auth/storage/entstore/ent/oauthtoken"
	"github.com/mwangaben/auth/storage/entstore/ent/predicate"
)

// OAuthTokenUpdate is the builder for updating OAuthToken entities.
type OAuthTokenUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthTokenMutation
}

// Where appends a list predicates to the OAuthTokenUpdate builder.
func (_u *OAuthTokenUpdate) Where(ps ...predicate.OAuthToken) *OAuthTokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OAuthTokenUpdate) SetUserID(v string) *OAuthTokenUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OAuthTokenUpdate) SetNillableUserID(v *string) *OAuthTokenUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthTokenUpdate) SetClientID(v string) *OAuthTokenUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthTokenUpdate) SetNillableClientID(v *string) *OAuthTokenUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// ClearClientID clears the value of the "client_id" field.
func (_u *OAuthTokenUpdate) ClearClientID() *OAuthTokenUpdate {
	_u.mutation.ClearClientID()
	return _u
}

// SetName sets the "name" field.
func (_u *OAuthTokenUpdate) SetName(v string) *OAuthTokenUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *OAuthTokenUpdate) SetNillableName(v *string) *OAuthTokenUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *OAuthTokenUpdate) ClearName() *OAuthTokenUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *OAuthTokenUpdate) SetScopes(v string) *OAuthTokenUpdate {
	_u.mutation.SetScopes(v)
	return _u
}

// SetNillableScopes sets the "scopes" field if the given value is not nil.
func (_u *OAuthTokenUpdate) SetNillableScopes(v *string) *OAuthTokenUpdate {
	if v != nil {
		_u.SetScopes(*v)
	}
	return _u
}

// ClearScopes clears the value of the "scopes" field.
func (_u *OAuthTokenUpdate) ClearScopes() *OAuthTokenUpdate {
	_u.mutation.ClearScopes()
	return _u
}

// SetRevoked sets the "revoked" field.
func (_u *OAuthTokenUpdate) SetRevoked(v bool) *OAuthTokenUpdate {
	_u.mutation.SetRevoked(v)
	return _u
}

// SetNillableRevoked sets the "revoked" field if the given value is not nil.
func (_u *OAuthTokenUpdate) SetNillableRevoked(v *bool) *OAuthTokenUpdate {
	if v != nil {
		_u.SetRevoked(*v)
	}
	return _u
}

// SetAccessToken sets the "access_token" field.
func (_u *OAuthTokenUpdate) SetAccessToken(v string) *OAuthTokenUpdate {
	_u.mutation.SetAccessToken(v)
	return _u
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (_u *OAuthTokenUpdate) SetNillableAccessToken(v *string) *OAuthTokenUpdate {
	if v != nil {
		_u.SetAccessToken(*v)
	}
	return _u
}

// SetRefreshToken sets the "refresh_token" field.
func (_u *OAuthTokenUpdate) SetRefreshToken(v string) *OAuthTokenUpdate {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_u *OAuthTokenUpdate) SetNillableRefreshToken(v *string) *OAuthTokenUpdate {
	if v != nil {
		_u.SetRefreshToken(*v)
	}
	return _u
}

// ClearRefreshToken clears the value of the "refresh_token" field.
func (_u *OAuthTokenUpdate) ClearRefreshToken() *OAuthTokenUpdate {
	_u.mutation.ClearRefreshToken()
	return _u
}

// SetAccessExpiresAt sets the "access_expires_at" field.
func (_u *OAuthTokenUpdate) SetAccessExpiresAt(v time.Time) *OAuthTokenUpdate {
	_u.mutation.SetAccessExpiresAt(v)
	return _u
}

// SetNillableAccessExpiresAt sets the "access_expires_at" field if the given value is not nil.
func (_u *OAuthTokenUpdate) SetNillableAccessExpiresAt(v *time.Time) *OAuthTokenUpdate {
	if v != nil {
		_u.SetAccessExpiresAt(*v)
	}
	return _u
}

// SetRefreshExpiresAt sets the "refresh_expires_at" field.
func (_u *OAuthTokenUpdate) SetRefreshExpiresAt(v time.Time) *OAuthTokenUpdate {
	_u.mutation.SetRefreshExpiresAt(v)
	return _u
}

// SetNillableRefreshExpiresAt sets the "refresh_expires_at" field if the given value is not nil.
func (_u *OAuthTokenUpdate) SetNillableRefreshExpiresAt(v *time.Time) *OAuthTokenUpdate {
	if v != nil {
		_u.SetRefreshExpiresAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthTokenUpdate) SetUpdatedAt(v time.Time) *OAuthTokenUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OAuthTokenMutation object of the builder.
func (_u *OAuthTokenUpdate) Mutation() *OAuthTokenMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthTokenUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthTokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthTokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthTokenUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthtoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthTokenUpdate) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := oauthtoken.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "OAuthToken.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := oauthtoken.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OAuthToken.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := oauthtoken.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OAuthToken.name": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthTokenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthtoken.Table, oauthtoken.Columns, sqlgraph.NewFieldSpec(oauthtoken.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(oauthtoken.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oauthtoken.FieldClientID, field.TypeString, value)
	}
	if _u.mutation.ClientIDCleared() {
		_spec.ClearField(oauthtoken.FieldClientID, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(oauthtoken.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(oauthtoken.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(oauthtoken.FieldScopes, field.TypeString, value)
	}
	if _u.mutation.ScopesCleared() {
		_spec.ClearField(oauthtoken.FieldScopes, field.TypeString)
	}
	if value, ok := _u.mutation.Revoked(); ok {
		_spec.SetField(oauthtoken.FieldRevoked, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AccessToken(); ok {
		_spec.SetField(oauthtoken.FieldAccessToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(oauthtoken.FieldRefreshToken, field.TypeString, value)
	}
	if _u.mutation.RefreshTokenCleared() {
		_spec.ClearField(oauthtoken.FieldRefreshToken, field.TypeString)
	}
	if value, ok := _u.mutation.AccessExpiresAt(); ok {
		_spec.SetField(oauthtoken.FieldAccessExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RefreshExpiresAt(); ok {
		_spec.SetField(oauthtoken.FieldRefreshExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthtoken.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthtoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthTokenUpdateOne is the builder for updating a single OAuthToken entity.
type OAuthTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthTokenMutation
}

// SetUserID sets the "user_id" field.
func (_u *OAuthTokenUpdateOne) SetUserID(v string) *OAuthTokenUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OAuthTokenUpdateOne) SetNillableUserID(v *string) *OAuthTokenUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthTokenUpdateOne) SetClientID(v string) *OAuthTokenUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthTokenUpdateOne) SetNillableClientID(v *string) *OAuthTokenUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// ClearClientID clears the value of the "client_id" field.
func (_u *OAuthTokenUpdateOne) ClearClientID() *OAuthTokenUpdateOne {
	_u.mutation.ClearClientID()
	return _u
}

// SetName sets the "name" field.
func (_u *OAuthTokenUpdateOne) SetName(v string) *OAuthTokenUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *OAuthTokenUpdateOne) SetNillableName(v *string) *OAuthTokenUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *OAuthTokenUpdateOne) ClearName() *OAuthTokenUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *OAuthTokenUpdateOne) SetScopes(v string) *OAuthTokenUpdateOne {
	_u.mutation.SetScopes(v)
	return _u
}

// SetNillableScopes sets the "scopes" field if the given value is not nil.
func (_u *OAuthTokenUpdateOne) SetNillableScopes(v *string) *OAuthTokenUpdateOne {
	if v != nil {
		_u.SetScopes(*v)
	}
	return _u
}

// ClearScopes clears the value of the "scopes" field.
func (_u *OAuthTokenUpdateOne) ClearScopes() *OAuthTokenUpdateOne {
	_u.mutation.ClearScopes()
	return _u
}

// SetRevoked sets the "revoked" field.
func (_u *OAuthTokenUpdateOne) SetRevoked(v bool) *OAuthTokenUpdateOne {
	_u.mutation.SetRevoked(v)
	return _u
}

// SetNillableRevoked sets the "revoked" field if the given value is not nil.
func (_u *OAuthTokenUpdateOne) SetNillableRevoked(v *bool) *OAuthTokenUpdateOne {
	if v != nil {
		_u.SetRevoked(*v)
	}
	return _u
}

// SetAccessToken sets the "access_token" field.
func (_u *OAuthTokenUpdateOne) SetAccessToken(v string) *OAuthTokenUpdateOne {
	_u.mutation.SetAccessToken(v)
	return _u
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (_u *OAuthTokenUpdateOne) SetNillableAccessToken(v *string) *OAuthTokenUpdateOne {
	if v != nil {
		_u.SetAccessToken(*v)
	}
	return _u
}

// SetRefreshToken sets the "refresh_token" field.
func (_u *OAuthTokenUpdateOne) SetRefreshToken(v string) *OAuthTokenUpdateOne {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_u *OAuthTokenUpdateOne) SetNillableRefreshToken(v *string) *OAuthTokenUpdateOne {
	if v != nil {
		_u.SetRefreshToken(*v)
	}
	return _u
}

// ClearRefreshToken clears the value of the "refresh_token" field.
func (_u *OAuthTokenUpdateOne) ClearRefreshToken() *OAuthTokenUpdateOne {
	_u.mutation.ClearRefreshToken()
	return _u
}

// SetAccessExpiresAt sets the "access_expires_at" field.
func (_u *OAuthTokenUpdateOne) SetAccessExpiresAt(v time.Time) *OAuthTokenUpdateOne {
	_u.mutation.SetAccessExpiresAt(v)
	return _u
}

// SetNillableAccessExpiresAt sets the "access_expires_at" field if the given value is not nil.
func (_u *OAuthTokenUpdateOne) SetNillableAccessExpiresAt(v *time.Time) *OAuthTokenUpdateOne {
	if v != nil {
		_u.SetAccessExpiresAt(*v)
	}
	return _u
}

// SetRefreshExpiresAt sets the "refresh_expires_at" field.
func (_u *OAuthTokenUpdateOne) SetRefreshExpiresAt(v time.Time) *OAuthTokenUpdateOne {
	_u.mutation.SetRefreshExpiresAt(v)
	return _u
}

// SetNillableRefreshExpiresAt sets the "refresh_expires_at" field if the given value is not nil.
func (_u *OAuthTokenUpdateOne) SetNillableRefreshExpiresAt(v *time.Time) *OAuthTokenUpdateOne {
	if v != nil {
		_u.SetRefreshExpiresAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthTokenUpdateOne) SetUpdatedAt(v time.Time) *OAuthTokenUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OAuthTokenMutation object of the builder.
func (_u *OAuthTokenUpdateOne) Mutation() *OAuthTokenMutation {
	return _u.mutation
}

// Where appends a list predicates to the OAuthTokenUpdate builder.
func (_u *OAuthTokenUpdateOne) Where(ps ...predicate.OAuthToken) *OAuthTokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthTokenUpdateOne) Select(field string, fields ...string) *OAuthTokenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthToken entity.
func (_u *OAuthTokenUpdateOne) Save(ctx context.Context) (*OAuthToken, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthTokenUpdateOne) SaveX(ctx context.Context) *OAuthToken {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthTokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthTokenUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthtoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthTokenUpdateOne) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := oauthtoken.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "OAuthToken.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := oauthtoken.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OAuthToken.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := oauthtoken.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OAuthToken.name": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthTokenUpdateOne) sqlSave(ctx context.Context) (_node *OAuthToken, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthtoken.Table, oauthtoken.Columns, sqlgraph.NewFieldSpec(oauthtoken.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OAuthToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthtoken.FieldID)
		for _, f := range fields {
			if !oauthtoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauthtoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(oauthtoken.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oauthtoken.FieldClientID, field.TypeString, value)
	}
	if _u.mutation.ClientIDCleared() {
		_spec.ClearField(oauthtoken.FieldClientID, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(oauthtoken.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(oauthtoken.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(oauthtoken.FieldScopes, field.TypeString, value)
	}
	if _u.mutation.ScopesCleared() {
		_spec.ClearField(oauthtoken.FieldScopes, field.TypeString)
	}
	if value, ok := _u.mutation.Revoked(); ok {
		_spec.SetField(oauthtoken.FieldRevoked, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AccessToken(); ok {
		_spec.SetField(oauthtoken.FieldAccessToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(oauthtoken.FieldRefreshToken, field.TypeString, value)
	}
	if _u.mutation.RefreshTokenCleared() {
		_spec.ClearField(oauthtoken.FieldRefreshToken, field.TypeString)
	}
	if value, ok := _u.mutation.AccessExpiresAt(); ok {
		_spec.SetField(oauthtoken.FieldAccessExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RefreshExpiresAt(); ok {
		_spec.SetField(oauthtoken.FieldRefreshExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthtoken.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &OAuthToken{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthtoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
