// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mwangaben/auth/storage/entstore/ent/oauthtoken"
	"github.com/mwangaben/auth/storage/entstore/ent/predicate"
)

// OAuthTokenDelete is the builder for deleting a OAuthToken entity.
type OAuthTokenDelete struct {
	config
	hooks    []Hook
	mutation *OAuthTokenMutation
}

// Where appends a list predicates to the OAuthTokenDelete builder.
func (_d *OAuthTokenDelete) Where(ps ...predicate.OAuthToken) *OAuthTokenDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OAuthTokenDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OAuthTokenDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OAuthTokenDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(oauthtoken.Table, sqlgraph.NewFieldSpec(oauthtoken.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OAuthTokenDeleteOne is the builder for deleting a single OAuthToken entity.
type OAuthTokenDeleteOne struct {
	_d *OAuthTokenDelete
}

// Where appends a list predicates to the OAuthTokenDelete builder.
func (_d *OAuthTokenDeleteOne) Where(ps ...predicate.OAuthToken) *OAuthTokenDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OAuthTokenDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{oauthtoken.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OAuthTokenDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
