// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mwangaben/auth/storage/entstore/ent/oauthpersonalaccesstoken"
	"github.com/mwangaben/auth/storage/entstore/ent/predicate"
)

// OAuthPersonalAccessTokenUpdate is the builder for updating OAuthPersonalAccessToken entities.
type OAuthPersonalAccessTokenUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthPersonalAccessTokenMutation
}

// Where appends a list predicates to the OAuthPersonalAccessTokenUpdate builder.
func (_u *OAuthPersonalAccessTokenUpdate) Where(ps ...predicate.OAuthPersonalAccessToken) *OAuthPersonalAccessTokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTokenID sets the "token_id" field.
func (_u *OAuthPersonalAccessTokenUpdate) SetTokenID(v string) *OAuthPersonalAccessTokenUpdate {
	_u.mutation.SetTokenID(v)
	return _u
}

// SetNillableTokenID sets the "token_id" field if the given value is not nil.
func (_u *OAuthPersonalAccessTokenUpdate) SetNillableTokenID(v *string) *OAuthPersonalAccessTokenUpdate {
	if v != nil {
		_u.SetTokenID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OAuthPersonalAccessTokenUpdate) SetUserID(v string) *OAuthPersonalAccessTokenUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OAuthPersonalAccessTokenUpdate) SetNillableUserID(v *string) *OAuthPersonalAccessTokenUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *OAuthPersonalAccessTokenUpdate) SetName(v string) *OAuthPersonalAccessTokenUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *OAuthPersonalAccessTokenUpdate) SetNillableName(v *string) *OAuthPersonalAccessTokenUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRevoked sets the "revoked" field.
func (_u *OAuthPersonalAccessTokenUpdate) SetRevoked(v bool) *OAuthPersonalAccessTokenUpdate {
	_u.mutation.SetRevoked(v)
	return _u
}

// SetNillableRevoked sets the "revoked" field if the given value is not nil.
func (_u *OAuthPersonalAccessTokenUpdate) SetNillableRevoked(v *bool) *OAuthPersonalAccessTokenUpdate {
	if v != nil {
		_u.SetRevoked(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OAuthPersonalAccessTokenUpdate) SetExpiresAt(v time.Time) *OAuthPersonalAccessTokenUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OAuthPersonalAccessTokenUpdate) SetNillableExpiresAt(v *time.Time) *OAuthPersonalAccessTokenUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthPersonalAccessTokenUpdate) SetUpdatedAt(v time.Time) *OAuthPersonalAccessTokenUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OAuthPersonalAccessTokenMutation object of the builder.
func (_u *OAuthPersonalAccessTokenUpdate) Mutation() *OAuthPersonalAccessTokenMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthPersonalAccessTokenUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthPersonalAccessTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthPersonalAccessTokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthPersonalAccessTokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthPersonalAccessTokenUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthpersonalaccesstoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *OAuthPersonalAccessTokenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(oauthpersonalaccesstoken.Table, oauthpersonalaccesstoken.Columns, sqlgraph.NewFieldSpec(oauthpersonalaccesstoken.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TokenID(); ok {
		_spec.SetField(oauthpersonalaccesstoken.FieldTokenID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(oauthpersonalaccesstoken.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(oauthpersonalaccesstoken.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Revoked(); ok {
		_spec.SetField(oauthpersonalaccesstoken.FieldRevoked, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthpersonalaccesstoken.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthpersonalaccesstoken.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthpersonalaccesstoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthPersonalAccessTokenUpdateOne is the builder for updating a single OAuthPersonalAccessToken entity.
type OAuthPersonalAccessTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthPersonalAccessTokenMutation
}

// SetTokenID sets the "token_id" field.
func (_u *OAuthPersonalAccessTokenUpdateOne) SetTokenID(v string) *OAuthPersonalAccessTokenUpdateOne {
	_u.mutation.SetTokenID(v)
	return _u
}

// SetNillableTokenID sets the "token_id" field if the given value is not nil.
func (_u *OAuthPersonalAccessTokenUpdateOne) SetNillableTokenID(v *string) *OAuthPersonalAccessTokenUpdateOne {
	if v != nil {
		_u.SetTokenID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OAuthPersonalAccessTokenUpdateOne) SetUserID(v string) *OAuthPersonalAccessTokenUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OAuthPersonalAccessTokenUpdateOne) SetNillableUserID(v *string) *OAuthPersonalAccessTokenUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *OAuthPersonalAccessTokenUpdateOne) SetName(v string) *OAuthPersonalAccessTokenUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *OAuthPersonalAccessTokenUpdateOne) SetNillableName(v *string) *OAuthPersonalAccessTokenUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRevoked sets the "revoked" field.
func (_u *OAuthPersonalAccessTokenUpdateOne) SetRevoked(v bool) *OAuthPersonalAccessTokenUpdateOne {
	_u.mutation.SetRevoked(v)
	return _u
}

// SetNillableRevoked sets the "revoked" field if the given value is not nil.
func (_u *OAuthPersonalAccessTokenUpdateOne) SetNillableRevoked(v *bool) *OAuthPersonalAccessTokenUpdateOne {
	if v != nil {
		_u.SetRevoked(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OAuthPersonalAccessTokenUpdateOne) SetExpiresAt(v time.Time) *OAuthPersonalAccessTokenUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OAuthPersonalAccessTokenUpdateOne) SetNillableExpiresAt(v *time.Time) *OAuthPersonalAccessTokenUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthPersonalAccessTokenUpdateOne) SetUpdatedAt(v time.Time) *OAuthPersonalAccessTokenUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OAuthPersonalAccessTokenMutation object of the builder.
func (_u *OAuthPersonalAccessTokenUpdateOne) Mutation() *OAuthPersonalAccessTokenMutation {
	return _u.mutation
}

// Where appends a list predicates to the OAuthPersonalAccessTokenUpdate builder.
func (_u *OAuthPersonalAccessTokenUpdateOne) Where(ps ...predicate.OAuthPersonalAccessToken) *OAuthPersonalAccessTokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthPersonalAccessTokenUpdateOne) Select(field string, fields ...string) *OAuthPersonalAccessTokenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthPersonalAccessToken entity.
func (_u *OAuthPersonalAccessTokenUpdateOne) Save(ctx context.Context) (*OAuthPersonalAccessToken, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthPersonalAccessTokenUpdateOne) SaveX(ctx context.Context) *OAuthPersonalAccessToken {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthPersonalAccessTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthPersonalAccessTokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthPersonalAccessTokenUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthpersonalaccesstoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *OAuthPersonalAccessTokenUpdateOne) sqlSave(ctx context.Context) (_node *OAuthPersonalAccessToken, err error) {
	_spec := sqlgraph.NewUpdateSpec(oauthpersonalaccesstoken.Table, oauthpersonalaccesstoken.Columns, sqlgraph.NewFieldSpec(oauthpersonalaccesstoken.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OAuthPersonalAccessToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthpersonalaccesstoken.FieldID)
		for _, f := range fields {
			if !oauthpersonalaccesstoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauthpersonalaccesstoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TokenID(); ok {
		_spec.SetField(oauthpersonalaccesstoken.FieldTokenID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(oauthpersonalaccesstoken.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(oauthpersonalaccesstoken.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Revoked(); ok {
		_spec.SetField(oauthpersonalaccesstoken.FieldRevoked, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthpersonalaccesstoken.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthpersonalaccesstoken.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &OAuthPersonalAccessToken{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthpersonalaccesstoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
