// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mwangaben/auth/storage/entstore/ent/oauthclient"
	"github.com/mwangaben/auth/storage/entstore/ent/predicate"
)

// OAuthClientUpdate is the builder for updating OAuthClient entities.
type OAuthClientUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthClientMutation
}

// Where appends a list predicates to the OAuthClientUpdate builder.
func (_u *OAuthClientUpdate) Where(ps ...predicate.OAuthClient) *OAuthClientUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *OAuthClientUpdate) SetName(v string) *OAuthClientUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *OAuthClientUpdate) SetNillableName(v *string) *OAuthClientUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSecret sets the "secret" field.
func (_u *OAuthClientUpdate) SetSecret(v string) *OAuthClientUpdate {
	_u.mutation.SetSecret(v)
	return _u
}

// SetNillableSecret sets the "secret" field if the given value is not nil.
func (_u *OAuthClientUpdate) SetNillableSecret(v *string) *OAuthClientUpdate {
	if v != nil {
		_u.SetSecret(*v)
	}
	return _u
}

// SetRedirectURI sets the "redirect_uri" field.
func (_u *OAuthClientUpdate) SetRedirectURI(v string) *OAuthClientUpdate {
	_u.mutation.SetRedirectURI(v)
	return _u
}

// SetNillableRedirectURI sets the "redirect_uri" field if the given value is not nil.
func (_u *OAuthClientUpdate) SetNillableRedirectURI(v *string) *OAuthClientUpdate {
	if v != nil {
		_u.SetRedirectURI(*v)
	}
	return _u
}

// ClearRedirectURI clears the value of the "redirect_uri" field.
func (_u *OAuthClientUpdate) ClearRedirectURI() *OAuthClientUpdate {
	_u.mutation.ClearRedirectURI()
	return _u
}

// SetPersonalAccessClient sets the "personal_access_client" field.
func (_u *OAuthClientUpdate) SetPersonalAccessClient(v bool) *OAuthClientUpdate {
	_u.mutation.SetPersonalAccessClient(v)
	return _u
}

// SetNillablePersonalAccessClient sets the "personal_access_client" field if the given value is not nil.
func (_u *OAuthClientUpdate) SetNillablePersonalAccessClient(v *bool) *OAuthClientUpdate {
	if v != nil {
		_u.SetPersonalAccessClient(*v)
	}
	return _u
}

// SetPasswordClient sets the "password_client" field.
func (_u *OAuthClientUpdate) SetPasswordClient(v bool) *OAuthClientUpdate {
	_u.mutation.SetPasswordClient(v)
	return _u
}

// SetNillablePasswordClient sets the "password_client" field if the given value is not nil.
func (_u *OAuthClientUpdate) SetNillablePasswordClient(v *bool) *OAuthClientUpdate {
	if v != nil {
		_u.SetPasswordClient(*v)
	}
	return _u
}

// SetRevoked sets the "revoked" field.
func (_u *OAuthClientUpdate) SetRevoked(v bool) *OAuthClientUpdate {
	_u.mutation.SetRevoked(v)
	return _u
}

// SetNillableRevoked sets the "revoked" field if the given value is not nil.
func (_u *OAuthClientUpdate) SetNillableRevoked(v *bool) *OAuthClientUpdate {
	if v != nil {
		_u.SetRevoked(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthClientUpdate) SetUpdatedAt(v time.Time) *OAuthClientUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OAuthClientMutation object of the builder.
func (_u *OAuthClientUpdate) Mutation() *OAuthClientMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthClientUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthClientUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthClientUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthClientUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthClientUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthclient.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *OAuthClientUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(oauthclient.Table, oauthclient.Columns, sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(oauthclient.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Secret(); ok {
		_spec.SetField(oauthclient.FieldSecret, field.TypeString, value)
	}
	if value, ok := _u.mutation.RedirectURI(); ok {
		_spec.SetField(oauthclient.FieldRedirectURI, field.TypeString, value)
	}
	if _u.mutation.RedirectURICleared() {
		_spec.ClearField(oauthclient.FieldRedirectURI, field.TypeString)
	}
	if value, ok := _u.mutation.PersonalAccessClient(); ok {
		_spec.SetField(oauthclient.FieldPersonalAccessClient, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PasswordClient(); ok {
		_spec.SetField(oauthclient.FieldPasswordClient, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Revoked(); ok {
		_spec.SetField(oauthclient.FieldRevoked, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthclient.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthclient.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthClientUpdateOne is the builder for updating a single OAuthClient entity.
type OAuthClientUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthClientMutation
}

// SetName sets the "name" field.
func (_u *OAuthClientUpdateOne) SetName(v string) *OAuthClientUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *OAuthClientUpdateOne) SetNillableName(v *string) *OAuthClientUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSecret sets the "secret" field.
func (_u *OAuthClientUpdateOne) SetSecret(v string) *OAuthClientUpdateOne {
	_u.mutation.SetSecret(v)
	return _u
}

// SetNillableSecret sets the "secret" field if the given value is not nil.
func (_u *OAuthClientUpdateOne) SetNillableSecret(v *string) *OAuthClientUpdateOne {
	if v != nil {
		_u.SetSecret(*v)
	}
	return _u
}

// SetRedirectURI sets the "redirect_uri" field.
func (_u *OAuthClientUpdateOne) SetRedirectURI(v string) *OAuthClientUpdateOne {
	_u.mutation.SetRedirectURI(v)
	return _u
}

// SetNillableRedirectURI sets the "redirect_uri" field if the given value is not nil.
func (_u *OAuthClientUpdateOne) SetNillableRedirectURI(v *string) *OAuthClientUpdateOne {
	if v != nil {
		_u.SetRedirectURI(*v)
	}
	return _u
}

// ClearRedirectURI clears the value of the "redirect_uri" field.
func (_u *OAuthClientUpdateOne) ClearRedirectURI() *OAuthClientUpdateOne {
	_u.mutation.ClearRedirectURI()
	return _u
}

// SetPersonalAccessClient sets the "personal_access_client" field.
func (_u *OAuthClientUpdateOne) SetPersonalAccessClient(v bool) *OAuthClientUpdateOne {
	_u.mutation.SetPersonalAccessClient(v)
	return _u
}

// SetNillablePersonalAccessClient sets the "personal_access_client" field if the given value is not nil.
func (_u *OAuthClientUpdateOne) SetNillablePersonalAccessClient(v *bool) *OAuthClientUpdateOne {
	if v != nil {
		_u.SetPersonalAccessClient(*v)
	}
	return _u
}

// SetPasswordClient sets the "password_client" field.
func (_u *OAuthClientUpdateOne) SetPasswordClient(v bool) *OAuthClientUpdateOne {
	_u.mutation.SetPasswordClient(v)
	return _u
}

// SetNillablePasswordClient sets the "password_client" field if the given value is not nil.
func (_u *OAuthClientUpdateOne) SetNillablePasswordClient(v *bool) *OAuthClientUpdateOne {
	if v != nil {
		_u.SetPasswordClient(*v)
	}
	return _u
}

// SetRevoked sets the "revoked" field.
func (_u *OAuthClientUpdateOne) SetRevoked(v bool) *OAuthClientUpdateOne {
	_u.mutation.SetRevoked(v)
	return _u
}

// SetNillableRevoked sets the "revoked" field if the given value is not nil.
func (_u *OAuthClientUpdateOne) SetNillableRevoked(v *bool) *OAuthClientUpdateOne {
	if v != nil {
		_u.SetRevoked(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthClientUpdateOne) SetUpdatedAt(v time.Time) *OAuthClientUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OAuthClientMutation object of the builder.
func (_u *OAuthClientUpdateOne) Mutation() *OAuthClientMutation {
	return _u.mutation
}

// Where appends a list predicates to the OAuthClientUpdate builder.
func (_u *OAuthClientUpdateOne) Where(ps ...predicate.OAuthClient) *OAuthClientUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthClientUpdateOne) Select(field string, fields ...string) *OAuthClientUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthClient entity.
func (_u *OAuthClientUpdateOne) Save(ctx context.Context) (*OAuthClient, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthClientUpdateOne) SaveX(ctx context.Context) *OAuthClient {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthClientUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthClientUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthClientUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthclient.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *OAuthClientUpdateOne) sqlSave(ctx context.Context) (_node *OAuthClient, err error) {
	_spec := sqlgraph.NewUpdateSpec(oauthclient.Table, oauthclient.Columns, sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OAuthClient.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthclient.FieldID)
		for _, f := range fields {
			if !oauthclient.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauthclient.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(oauthclient.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Secret(); ok {
		_spec.SetField(oauthclient.FieldSecret, field.TypeString, value)
	}
	if value, ok := _u.mutation.RedirectURI(); ok {
		_spec.SetField(oauthclient.FieldRedirectURI, field.TypeString, value)
	}
	if _u.mutation.RedirectURICleared() {
		_spec.ClearField(oauthclient.FieldRedirectURI, field.TypeString)
	}
	if value, ok := _u.mutation.PersonalAccessClient(); ok {
		_spec.SetField(oauthclient.FieldPersonalAccessClient, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PasswordClient(); ok {
		_spec.SetField(oauthclient.FieldPasswordClient, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Revoked(); ok {
		_spec.SetField(oauthclient.FieldRevoked, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthclient.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &OAuthClient{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthclient.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
