// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/mwangaben/auth/storage/entstore/ent/oauthclient"
	"github.com/mwangaben/auth/storage/entstore/ent/oauthpersonalaccesstoken"
	"github.com/mwangaben/auth/storage/entstore/ent/oauthtoken"
	"github.com/mwangaben/auth/storage/entstore/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	oauthclientFields := schema.OAuthClient{}.Fields()
	_ = oauthclientFields
	// oauthclientDescPersonalAccessClient is the schema descriptor for personal_access_client field.
	oauthclientDescPersonalAccessClient := oauthclientFields[4].Descriptor()
	// oauthclient.DefaultPersonalAccessClient holds the default value on creation for the personal_access_client field.
	oauthclient.DefaultPersonalAccessClient = oauthclientDescPersonalAccessClient.Default.(bool)
	// oauthclientDescPasswordClient is the schema descriptor for password_client field.
	oauthclientDescPasswordClient := oauthclientFields[5].Descriptor()
	// oauthclient.DefaultPasswordClient holds the default value on creation for the password_client field.
	oauthclient.DefaultPasswordClient = oauthclientDescPasswordClient.Default.(bool)
	// oauthclientDescRevoked is the schema descriptor for revoked field.
	oauthclientDescRevoked := oauthclientFields[6].Descriptor()
	// oauthclient.DefaultRevoked holds the default value on creation for the revoked field.
	oauthclient.DefaultRevoked = oauthclientDescRevoked.Default.(bool)
	// oauthclientDescCreatedAt is the schema descriptor for created_at field.
	oauthclientDescCreatedAt := oauthclientFields[7].Descriptor()
	// oauthclient.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauthclient.DefaultCreatedAt = oauthclientDescCreatedAt.Default.(func() time.Time)
	// oauthclientDescUpdatedAt is the schema descriptor for updated_at field.
	oauthclientDescUpdatedAt := oauthclientFields[8].Descriptor()
	// oauthclient.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	oauthclient.DefaultUpdatedAt = oauthclientDescUpdatedAt.Default.(func() time.Time)
	// oauthclient.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	oauthclient.UpdateDefaultUpdatedAt = oauthclientDescUpdatedAt.UpdateDefault.(func() time.Time)
	oauthpersonalaccesstokenFields := schema.OAuthPersonalAccessToken{}.Fields()
	_ = oauthpersonalaccesstokenFields
	// oauthpersonalaccesstokenDescRevoked is the schema descriptor for revoked field.
	oauthpersonalaccesstokenDescRevoked := oauthpersonalaccesstokenFields[4].Descriptor()
	// oauthpersonalaccesstoken.DefaultRevoked holds the default value on creation for the revoked field.
	oauthpersonalaccesstoken.DefaultRevoked = oauthpersonalaccesstokenDescRevoked.Default.(bool)
	// oauthpersonalaccesstokenDescCreatedAt is the schema descriptor for created_at field.
	oauthpersonalaccesstokenDescCreatedAt := oauthpersonalaccesstokenFields[6].Descriptor()
	// oauthpersonalaccesstoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauthpersonalaccesstoken.DefaultCreatedAt = oauthpersonalaccesstokenDescCreatedAt.Default.(func() time.Time)
	// oauthpersonalaccesstokenDescUpdatedAt is the schema descriptor for updated_at field.
	oauthpersonalaccesstokenDescUpdatedAt := oauthpersonalaccesstokenFields[7].Descriptor()
	// oauthpersonalaccesstoken.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	oauthpersonalaccesstoken.DefaultUpdatedAt = oauthpersonalaccesstokenDescUpdatedAt.Default.(func() time.Time)
	// oauthpersonalaccesstoken.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	oauthpersonalaccesstoken.UpdateDefaultUpdatedAt = oauthpersonalaccesstokenDescUpdatedAt.UpdateDefault.(func() time.Time)
	oauthtokenFields := schema.OAuthToken{}.Fields()
	_ = oauthtokenFields
	// oauthtokenDescRevoked is the schema descriptor for revoked field.
	oauthtokenDescRevoked := oauthtokenFields[5].Descriptor()
	// oauthtoken.DefaultRevoked holds the default value on creation for the revoked field.
	oauthtoken.DefaultRevoked = oauthtokenDescRevoked.Default.(bool)
	// oauthtokenDescCreatedAt is the schema descriptor for created_at field.
	oauthtokenDescCreatedAt := oauthtokenFields[9].Descriptor()
	// oauthtoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauthtoken.DefaultCreatedAt = oauthtokenDescCreatedAt.Default.(func() time.Time)
	// oauthtokenDescUpdatedAt is the schema descriptor for updated_at field.
	oauthtokenDescUpdatedAt := oauthtokenFields[10].Descriptor()
	// oauthtoken.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	oauthtoken.DefaultUpdatedAt = oauthtokenDescUpdatedAt.Default.(func() time.Time)
	// oauthtoken.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	oauthtoken.UpdateDefaultUpdatedAt = oauthtokenDescUpdatedAt.UpdateDefault.(func() time.Time)
}
